import Foundation

/// Persistent, cross-meeting speaker registry. A voice heard in one meeting
/// is matched against every stored embedding by cosine similarity — this is
/// what lets a renamed "Speaker 1" come back as "Alice" in a later, unrelated
/// recording, since the table isn't scoped to a meeting.
final class VoiceLibrary {
    static let shared = VoiceLibrary()

    private init() {}

    /// Ensures the reserved "Me" row exists (mic track, no embedding needed —
    /// Wffl never diarizes its own microphone).
    func ensureMeSpeaker() {
        if let existing = Database.shared.allSpeakers().first(where: { $0.id == Speaker.meId }) {
            if existing.name != "Me" {
                Database.shared.renameSpeaker(id: Speaker.meId, name: "Me")
            }
            return
        }
        let now = Date()
        Database.shared.upsert(Speaker(id: Speaker.meId, name: "Me", embedding: [], createdAt: now, updatedAt: now))
    }

    static func canRename(speakerID: String) -> Bool {
        speakerID != Speaker.meId
    }

    /// Returns only speakers the user has explicitly named. Automatically
    /// generated "Speaker N" rows are meeting-local placeholders and must
    /// never make an unrelated future voice look like a known person.
    static func matchCandidates(from speakers: [Speaker]) -> [Speaker] {
        speakers.filter {
            $0.id != Speaker.meId &&
            !$0.embedding.isEmpty &&
            !isAutoGeneratedName($0.name)
        }
    }

    private static func isAutoGeneratedName(_ name: String) -> Bool {
        guard name.hasPrefix("Speaker ") else { return false }
        return Int(name.dropFirst("Speaker ".count)) != nil
    }

    /// Matches an embedding against human-named speakers; returns the best
    /// match above `Prefs.diarizationThreshold`, or creates and stores the
    /// next "Speaker N" if no named voice is close enough.
    func matchOrCreate(embedding: [Float]) -> Speaker {
        let candidates = Self.matchCandidates(from: Database.shared.allSpeakers())
        if let (best, score) = candidates
            .map({ ($0, Self.cosineSimilarity($0.embedding, embedding)) })
            .max(by: { $0.1 < $1.1 }),
           score >= Prefs.diarizationThreshold {
            return best
        }

        return newSpeaker(embedding: embedding)
    }

    /// Persists a new, automatically named speaker for a previously unseen
    /// diarization cluster. It is deliberately separate from matching so a
    /// caller can enforce one-to-one matching within a meeting first.
    func newSpeaker(embedding: [Float]) -> Speaker {
        let existingCount = Database.shared.allSpeakers().filter { $0.id != Speaker.meId }.count
        let speaker = Speaker.new(name: "Speaker \(existingCount + 1)", embedding: embedding)
        Database.shared.upsert(speaker)
        return speaker
    }

    func rename(_ speaker: Speaker, to name: String) {
        guard Self.canRename(speakerID: speaker.id) else { return }
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return }
        Database.shared.renameSpeaker(id: speaker.id, name: trimmed)
    }

    static func cosineSimilarity(_ a: [Float], _ b: [Float]) -> Float {
        guard a.count == b.count, !a.isEmpty else { return 0 }
        var dot: Float = 0, normA: Float = 0, normB: Float = 0
        for i in 0..<a.count {
            dot += a[i] * b[i]
            normA += a[i] * a[i]
            normB += b[i] * b[i]
        }
        guard normA > 0, normB > 0 else { return 0 }
        return dot / (normA.squareRoot() * normB.squareRoot())
    }
}
